### ISSUE TITLE
Formatting nominatim address

### ISSUE THREAD

**Issue by adam21** [OpenCageData/address-formatting#10]
Hello everybody,

It will be great if I can format my Nominatim  address with address-formatting ! 

Is this possible ? is there any tutorial ? 

Help please

**Comment by freyfogle** [comment]
Hi @adam21 it's totally possible. 
address-formatting is just a set of mustache templates. You need a code library to take your output and apply it to the templates. Currently there is only one that I'm aware of, it's Geo::Address::Formatter in perl, see https://metacpan.org/pod/Geo::Address::Formatter

We would love to see more libraries in other languages.
