### ISSUE TITLE
Think about address grids

### ISSUE THREAD

**Issue by jidanni** [OpenCageData/address-formatting#105]
https://www.jidanni.org/geo/house_numbering/grids/define.html discusses address grids.
Maybe you might want to employ some of the ideas, or indeed start the "EPSG-like" database of address grids!

I'm saying that considering address grids will improve your geocoding, forward and reverse.

https://github.com/OSGeo/gdal/pull/9862 is a simple example of the power of address grids.

**Comment by freyfogle** [comment]
Hello, interesting read. 

Not sure of the relevance here in the address-formatting repo though, so I will close this issue.

If you have suggestions about improving OpenCage, [the OpenCage feedback form ](https://opencagedata.com/contact) is the place to submit them. No need to resubmit this there though, I have now read it. To date we have never had a customer ask for this kind of "grid ref geocoding", so not likely to take any action until that happens.
