### ISSUE TITLE
Breaking: Duplicate YAML key in CA abbreviations

### ISSUE THREAD

**Issue by r0bin** [OpenCageData/address-formatting#107]
An addition to `conf/abbreviations/ca.yaml` in bccdfdd breaks applications loading the abbreviation files due to a duplicate `Travessia ` YAML key:

https://github.com/OpenCageData/address-formatting/blob/bccdfddf82501d5eb004e26e19d056ae3fb81fcd/conf/abbreviations/ca.yaml#L19-L22

**Comment by freyfogle** [comment]
yes, good point. Have just committed a fix. Will see about adding a test for this
