### ISSUE TITLE
Trailing slash in Indian addresses

### ISSUE THREAD

**Issue by rkoeze** [OpenCageData/address-formatting#114]
Hi folks,

First of all, thanks for maintaining this project! It's greatly appreciated.

I maintain [the java implementation](https://github.com/placemarkt/address-formatter-java) and [was recently made aware](https://github.com/placemarkt/address-formatter-java/issues/7) of the following case: when Indian address parts contain a city but not a postcode the result will include a trailing slash. So for instance:

```
country_code: 'IN',
road: 'Baner',
city: 'Pune',
state: 'Maharashtra',
country: 'India',
```

Will be formatted as this:

```
Baner
Pune -
Maharashtra
India
```

I'm not 100% sure what is the correct output here, but I _suspect_ that the trailing slash should be removed in this case. Is that correct? If so, would it make sense to contain a rule in the `postformat_replace` field for this case or do something like this:

```
{{#first}} {{{city}}} || {{{town}}} || {{{village}}} || {{{hamlet}}} {{/first}} {{#postcode}} - {{{postcode}}} {{/postcode}} 
```

I've confirmed that this also occurs in [at least one other implementation](https://github.com/fragaria/address-formatter).

**Comment by freyfogle** [comment]
Thanks for the bug report. Will create a test case and come back to you in next day or so.
