### ISSUE TITLE
German address abbreviation not correct

### ISSUE THREAD

**Issue by K-Ko** [OpenCageData/address-formatting#115]
`/conf/abbreviations/de.yaml`

    road:
         Platz: Pl

I stumbled across the fact that the following address is shortened incorrectly, correct is

    Willy-Brandt-Platz 6
    81829 München

but  formatted result is

    Willy-Brandt-Pl 6
    81829 München

https://www.openstreetmap.org/search?query=Willy-Brandt-Platz%206%2C%2081829%20M%C3%BCnchen

**Comment by freyfogle** [comment]
hmm, ja. Thanks for making us aware. 

Ok, will add a test case and get a fix out in a few days but it will be to [the perl parser](https://metacpan.org/pod/Geo::Address::Formatter). Will be up to each language parser to obey the test.

**Comment by freyfogle** [comment]
Haven't forgotten about this, just busy with travel and other things. More soon.

**Comment by K-Ko** [comment]
May be there is another blurring

`Rue des Voituriers` becomes `r des Voituriers`, but OSM:

![image](https://github.com/user-attachments/assets/d587751b-406b-4d35-abad-479bd7be6937)

**Comment by mtmail** [comment]
@K-Ko Can you open a seprate github issue? In which city,country did you find the street?

**Comment by K-Ko** [comment]
Done, #117 , #118

**Comment by freyfogle** [comment]
the original German issue is now solved in the latest version of the perl parser (Geo::Address::Formatter) and there is now a test in `testcases/abbreviations/de.yaml`
