### ISSUE TITLE
French abbreviations not correct

### ISSUE THREAD

**Issue by K-Ko** [OpenCageData/address-formatting#117]
Correct

    Rue des Voituriers
    67500 Haguenau

Incorrect

    r des Voituriers
    67500 Haguenau

https://www.openstreetmap.org/search?query=Rue%20des%20Voituriers%2067500%20Haguenau

**Comment by freyfogle** [comment]
ok, I looked into this.

a. be aware that if you are unhapppy with any abbreviation you can change your local configuration, in this case the file `conf/abbreviations/fr.yaml` T

b. Have now added a test for this specific case, see:
https://github.com/OpenCageData/address-formatting/blob/master/testcases/abbreviations/fr.yaml#L2

and it passes with the newest `fr` abbreviation conf
https://github.com/OpenCageData/address-formatting/blob/master/conf/abbreviations/fr.yaml#L7

If you have more bugs please submit test cases. Thanks
