### ISSUE TITLE
Duplicated keys in `first` lambda

### ISSUE THREAD

**Issue by ede-wolf-gls** [OpenCageData/address-formatting#120]
I checked the worldwide templates and found 2 places, where a key is 2 times in the `first` lambda (one time in combination with a different key). What should be the expected behavior of the lambda function, depending on different input?
One time in [`generic2`](https://github.com/OpenCageData/address-formatting/blob/723422ff3c08ce3af75fe99e613c6f834248d039/conf/countries/worldwide.yaml#L16)
and one time if [`SG.addressTemplate`](https://github.com/OpenCageData/address-formatting/blob/723422ff3c08ce3af75fe99e613c6f834248d039/conf/countries/worldwide.yaml#L1793C9-L1793C72)
>  {{#first}} {{{house}}}, {{{quarter}}} || {{{house}}} {{/first}}

As far as I see, most implementations just output the first element, that has any content (so always the first one, because in contains a `,`), so the whole lambda could just be reduced to 
> {{{house}}}, {{{quarter}}}

because it's irrelevant, if `quarter` is defined or not.

**Comment by freyfogle** [comment]
You are right, thanks for spotting. Fixed in https://github.com/OpenCageData/address-formatting/commit/2bf36d10da12455dd77be2d7d679bda8513bc915

**Comment by ede-wolf-gls** [comment]
Thank you
