### ISSUE TITLE
Best places to research national address formatting standards?

### ISSUE THREAD

**Issue by riordan** [OpenCageData/address-formatting#16]
@freyfogle: I'm wondering what research resources you'd recommend for hunting down local address formatting standards?

**Comment by freyfogle** [comment]
This is ok
http://www.addressdoctor.com/en/countries-data/address-formats.html

but in general just searching. Often I find a bank or government entity and look at how they display the address on their site. It is tedious, hence why I typically do one country a day. But now we have done almost all major countries. The exception is Asia where I haven't yet focused. Will get there once I complete Europe and Latam, probably in two weeks or so.
