### ISSUE TITLE
Component key specified by `_type` may not be present

### ISSUE THREAD

**Issue by tylrtrmbl** [OpenCageData/address-formatting#29]
This is similar to #28. See it for context.

In #28 I reported that `_type` in the `components` section of a geocoding result may match an alias for a component, instead of the component itself. This has been fixed.

This issue is to report that `_type` may be present, but not refer to *any* component __or alias__ for that component. See the components dictionary for (43.08226365175275, -87.8847851373871):

```
{
    "_type" : "building",
    "city" : "Milwaukee",
    "country" : "United States of America",
    "country_code" : "us",
    "county" : "Milwaukee County",
    "house_number" : "2028",
    "postcode" : "53211",
    "road" : "East Edgewood Avenue",
    "state" : "Wisconsin"
}
```

Notice that `_type` is set to `building`, but neither `building` nor any of its [aliases](https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml) (`house` or `public_building`) are present.

Please advise. :)

cc/ @freyfogle

**Comment by freyfogle** [comment]
This is expected behaviour. 
If there is a house_number, we assume there must be a building. 

The resulting formatted address is 
"2028 East Edgewood Avenue, Milwaukee, WI 53211, United States of America"
which is a perfectly valid address.

**Comment by tylrtrmbl** [comment]
I guess I'm okay with that. Thanks @freyfogle!
