### ISSUE TITLE
Update Incorrect Data

### ISSUE THREAD

**Issue by ldgbc** [OpenCageData/address-formatting#46]
Hi,

Recently started using OpenCage API (Free Account) with Free Key (2500 limits), using Yetiforce v4.30 as frontend.

I only tested a few search but notice that some of the search result is incorrect. For example the postcode, how can I update/contribute to the correct data?

Thank you.

See: https://github.com/YetiForceCompany/YetiForceCRM/issues/7289

**Comment by freyfogle** [comment]
Hi, please send issues related to opencage's results to support@opencagedata.com 

Please send a specific example - what you searched for, what result you got, what result you expected. 

This repo is only for address formatting issues.

**Comment by ldgbc** [comment]
@freyfogle Thanks. 

Bit of a waste to go all through Email channel rather than a ticketing channel. Who know how many other people going to send in the same question.

**Comment by freyfogle** [comment]
@ldgbc the point is, this is just one of many tools used by OpenCage. It is not the place to report OpenCage bugs.
