### ISSUE TITLE
Generic Address Lines

### ISSUE THREAD

**Issue by koab** [OpenCageData/address-formatting#47]
Hello,
Firstly thanks for such a great project. My question is about usage of data from a generic address form where use can enter:

- Address line 1
- Address line 2
- City
- State
- Country
- Postal Code

I am curious about how can I use address line 1 and address line 2 data on address templates. Is it would be correct, to certain extend, placing address line 1 as street/street_name and address line 2 as house/building?

**Comment by freyfogle** [comment]
Hi @koab,

first up, thanks for the kind words about the project, we welcome any contribution you may have.

Regarding your question - I guess it depends on what your users usually put in "Address line 1" and "Address line 2". I wonder if it might make more sense to give them more specific labels like "street" and "house name". Hard for me to say without knowing your use-case and who your target audience is. Sorry I can't really be more specific.
