### ISSUE TITLE
Postal address formatting

### ISSUE THREAD

**Issue by MathieuLoutre** [OpenCageData/address-formatting#48]
This is such a great resource! This [link](http://www.bitboost.com/ref/international-address-formats.html#Formats) is really useful but very intimidating and it seems like you've gone to great length to standardise things already.

I know the repo specifically says this is not for postal delivery but I wonder: how far is it from being useable for that purpose?

I've written a small Node.js script that uses this database for address formatting but only realise afterwards it wasn't fit for purpose. However, in most instances it seems extremely close. 

How did you source the current formatting? How different is it from postal formatting? I'd be keen to fork/contribute in order to add the missing bits.

**Comment by freyfogle** [comment]
Hi @MathieuLoutre glad you like the project. 

I'd love to see - and link to  - your node script. Please can you post the URL?

The thing about postal delivery is just that that was not our use case. Ours is to format categorized geographic inputs. We make no attempt, for example, to determine if an address (or postcode, or town, or whatever) really exists. That said, there is no particular reason you could not use it for postal delivery, the point is just that we didn't design it for that use case. 

Final thing - your profile shows you as being in London you might want to come along to the geo meetup we run every few months: [#geomob](https://geomobldn.org)

Our next event is [on 16th January](https://geomobldn.org/post/jan-16th-2019-geomob-details). The talks are fun and the beers are on us. Hope you can join us then or at a future #geomob.

**Comment by freyfogle** [comment]
Hi, 

if memory serves we just assumed you can append country at end, or not, depending on use case (national versus international).

re: fallback you can follow all of our logic here: https://github.com/OpenCageData/perl-Geo-Coder-OpenCage

There is no single source, it was painful work, country by country doing the research. Some countries have well defined standards, many others unfortunately do not. We welcome all test cases where you think we can improve. 

I look forward to meeting you in January.

**Comment by MathieuLoutre** [comment]
Hello! Took another look at my script and it turns out my `{{#first}}` helper was broken hence the missing country information in some addresses. I've fixed it all up and now it seems to output exactly what I need.

Here's the code I've used: https://gist.github.com/MathieuLoutre/27376d65292906f7a38a401e07a9ad0e

This is purely based on intuition, reading the format etc. Just needed something quick. However, looking at the link above there are many more things to take into account to make this useable. Still, hopefully that can get someone started if I don't get the time to work on this further.

**Comment by freyfogle** [comment]
thanks Mathieu, 

yes, there are edge cases where the logic can get a bit complicated. Such is the joy of geo.
I actually have been thinking of a few little improvements, perhaps over xmas I will find the time. 

Thanks for sending the link, but one request - can you stick it in a repo? Something more permanent than a gist?

**Comment by freyfogle** [comment]
closing this issue. no further action
