### ISSUE TITLE
Typo in address formatting Angola->Afghanistan

### ISSUE THREAD

**Issue by samuelleach** [OpenCageData/address-formatting#54]
Hello Ed and team,

There appears to be a typo in one of the comments in the worldwide.yaml file

https://github.com/OpenCageData/address-formatting/blob/master/conf/countries/worldwide.yaml#L243

The comment should read `# Afghanistan` not `# Angola`.

Context: I found this typo when testing the quality of the formatted address in some locations in Kabul. I was trying to understand what formatted address template is used in this country.

**Comment by freyfogle** [comment]
well spotted, you are of course entirely correct. Committing a fix now
