### ISSUE TITLE
UAE test address in Dubai

### ISSUE THREAD

**Issue by samuelleach** [OpenCageData/address-formatting#55]
The following coordinate 25.0299178,55.1872123 would be expected by a local resident I know to include the words `International Media Production Zone` within the opencage formatted address. Right now opencage returns `Dubai, United Arab Emirates` for the formatted address.

UAE seems to use the `generic5` address template (https://github.com/OpenCageData/address-formatting/blob/master/conf/countries/worldwide.yaml#L37) which is not making use of the `suburb` field, in which the data `International Media Production Zone` can be found. That data is typically visible on maps like OSM and others.

I don't know how generalisable this test case is, but maybe it's helpful.

**Comment by samuelleach** [comment]
In addition, the underlying OSM data is out of date (out of scope of this ticket). Since a few years the IMPZ is known as Dubai Production City following a renaming.

**Comment by freyfogle** [comment]
thanks for the specific example, this is great. Please can you correct OSM if you have local knowledge? Will try to make a test for this by Monday.

**Comment by samuelleach** [comment]
For info - I've attempted to update OSM based on this local knowledge from a resident there.

**Comment by freyfogle** [comment]
a fix is now committed and live on OpenCage
https://github.com/OpenCageData/address-formatting/commit/d84ba31c744cffe495310bfc4ce722cf9b9a090a

**Comment by samuelleach** [comment]
Confirmed on the OpenCage demo: https://opencagedata.com/demo

I also confirm that my change to the OSM data https://github.com/OpenCageData/address-formatting/issues/55#issuecomment-513263941 is now propagating through to OpenCage.

Kudos!

It's very motivating to submit feedback to OpenCage and edits when you see the changes implemented in less than 24 hours.

**Comment by freyfogle** [comment]
thanks for the kind words, we do our best. You also got a bit lucky on the timing of the OSM update, normally we are 24-48 hours behind
