### ISSUE TITLE
Iraq - Erbil address test cases

### ISSUE THREAD

**Issue by samuelleach** [OpenCageData/address-formatting#56]
Hello Ed and team,

We're seeing some issues with address formatting in Erbil in Iraq where I have colleagues with local knowledge.

- There may be one issue relating to the fact that Erbil doesn't appear to have a city boundary. Erbil is a node in OSM, not a 'way' (boundary) https://www.openstreetmap.org/node/599019138 Do you think this might cause issues in formatting?

- A specific case we are looking at is in the 'English Village' in Erbil. This location:

36.19137, 43.97445

is being formatted by opencage as

`391, Erbil, 44001, Iraq`

It would be expected to be

`391 English Village, Erbil, 44001, Iraq`

You can see that the English Village is appearing in the `neighbourhood` field of this location.

- I think there may be other issues in Erbil with the neighbourhood or suburb not being used in the formatted address. For instance the Aramex Post office (location 36.2239829,43.99235 and OSM https://www.openstreetmap.org/node/6011838385#map=19/36.22502/43.99257)  is in the Ankawa `neighbourhood` but opencage returns for the formatted address:

`Iraqi Kurdistan, 44003, Iraq`
i.e. Not obviously in Ankawa or Erbil itself.

Let me know if this information is enough to improve the formatted address. I can hopefully provide more examples in the near future.

**Comment by freyfogle** [comment]
nice one. We are on it.

**Comment by samuelleach** [comment]
Great! Just for further info:

- This is a list of postcodes in Iraq https://en.wikipedia.org/wiki/List_of_postal_codes_in_Iraq

- So postcode 44003, above, is carrying the information about Ankawa.
- And 44001, above, is carrying the information about Erbil.

But still, one expects to see the district written out.

**Comment by freyfogle** [comment]
ok, that formatting fix is now live

**Comment by samuelleach** [comment]
Thanks confirmed. I see the improvements to the Iraq address template via https://github.com/OpenCageData/address-formatting/commit/0b9d2ac65e3eaf1e78adae8200a2c8bc15f692e5
