### ISSUE TITLE
China Postal Code

### ISSUE THREAD

**Issue by crismani** [OpenCageData/address-formatting#59]
Hi Guys,

ZIP is required in China, but it seems to be missing from the YAML mapping.

The format in China according to UPU is Postal code | Province / City / Town / Village

http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/chnEn.pdf

**Comment by freyfogle** [comment]
Thanks, fix committed, but what we really need for CN are more test cases. Not an area of the world I have much experience with, unfortunately

**Comment by crismani** [comment]
@freyfogle 

Thanks for the quick fix. What do you mean by more test cases though? To see if the script is able to format addresses correctly?

**Comment by freyfogle** [comment]
yes, here are testcases for every country: 
https://github.com/OpenCageData/address-formatting/tree/master/testcases/countries

Some countries have many, China has only one
