### ISSUE TITLE
Hong Kong address format issue (js library)

### ISSUE THREAD

**Issue by jack-booxi** [OpenCageData/address-formatting#72]
Hi, team
The version I am using is src="https://unpkg.com/@fragaria/address-formatter@2.3.0"
The config example is
var formatted = window.addressFormatter.format({
"houseNumber": "",
"road": "211 Test Street",
"neighbourhood": "",
"city": "Hong Kong",
"postcode": "",
"county": "",
"state": "",
"country": "Hong Kong",
"countryCode": "HK",
}, {
output: 'array'
});
The output result will just show "211 Test Street".
Thank you for your attention!

**Comment by freyfogle** [comment]
nice bug, thanks. I am able to recreate the error and having a look now. 

more soon.

**Comment by freyfogle** [comment]
a fix is now checked in 
https://github.com/OpenCageData/address-formatting/commit/36127895f27faa3231614dcab544227c577e8a11

thanks for submitting the bug
