### ISSUE TITLE
Request: Ways to return geocode results at [city / town / community] level

### ISSUE THREAD

**Issue by sbutler-gh** [OpenCageData/address-formatting#77]
I'm interested in using OpenCage to geocode the [city / town / community] that a user is in.

Referencing the Response Format example in the documentation, with a query like this:

https://api.opencagedata.com/geocode/v1/json?q=-22.6792%2C+14.5272&key=YOUR-API-KEY&pretty=1

I'd be interested in returning data like this:

            "city" : "Swakopmund",
            "country" : "Namibia",
            "country_code" : "na",
            "postcode" : "13001",
            "state" : "Erongo Region",
            
As well as the geojson geometry and coordinates for the **boundaries** of Swakopmund.

This is data that [Nominatim](https://nominatim.org/release-docs/develop/api/Reverse/) offers (specified by the `zoom` parameter to control the results), and I think it would be quite useful in OpenCage as well.

Just wanted to share in case this is possible!

P.S. Recently came across OpenCage, love what you've built!  Great job on the site, the story, the copy, the documentation, the UX, the climate commitments, everything.  Looking forward to getting more involved!

**Comment by freyfogle** [comment]
Thanks for the kind words, but this repo is NOT the place for general questions about OpenCage and feature requests for the OpenCage Geocoding API. Please [use the OpenCage contact form](https://opencagedata.com/contact), and keep this repo for issues relating to address-formatting. 

Thank you.

**Comment by freyfogle** [comment]
I have now sent an email with a detailed answer to your question to the email address listed in your Github profile.
