### ISSUE TITLE
Request: Add Wikidata IDs to Response Format

### ISSUE THREAD

**Issue by sbutler-gh** [OpenCageData/address-formatting#78]
Would it be possible to add [Wikidata IDs](https://www.wikidata.org/wiki/Wikidata:OpenStreetMap) to the OpenCage [response format](https://opencagedata.com/api#response)?

**Comment by freyfogle** [comment]
Hi,

why are you filing this in this repo? This is not the place for general OpenCage feature requests or questions. 
This repo is for address-formatting template questions.
Please use [the OpenCage contact form](https://opencagedata.com/contact) for general questions like this.

Nevertheless, [we do include the wikidata id as an annotation](https://opencagedata.com/api#wikidata) if possible (obviously not every thing  or place has a wikidata id)
