### ISSUE TITLE
Add secondary address unit designators next to delivery address

### ISSUE THREAD

**Issue by massimoadriaens** [OpenCageData/address-formatting#85]
I have a requirement where I need to put an optional secondary address unit designator next to the delivery address.
I assume this needs to put in 'house' variable but this is set on the line before the delivery address.
Right now I add it in on the same line after the delivery address through post processing.

Actual situation :
_**Unit 5**_
1535 Ellison Bridge Rd
Sardis, GA 30456

Requirement : 
1535 Ellison Bridge Rd _**Unit 5**_
Sardis, GA 30456

Is there a way I can achieve this without postprocessing?

thanks in advance!

**Comment by freyfogle** [comment]
Hi, 

no, currently there is no way to accomplish this without postprocessing. 

I guess the solution would be to add a tag like `{{{unit}}}` to the template used for formatting.
