### ISSUE TITLE
Panama becomes Panama City; Panama City becomes Panama City City?

### ISSUE THREAD

**Issue by brentodd** [OpenCageData/address-formatting#97]
It looks like the replacement here: https://github.com/OpenCageData/address-formatting/blob/b87b26c031c3b96ceb9c105d0ab6cfba953cf8eb/conf/countries/worldwide.yaml#L1560 replaces the word "Panama" with "Panama City", without accounting for the possibility that " City" is already present - resulting in a doubling up of the word "City".

**Comment by freyfogle** [comment]
well spotted, but any chance you can submit a test case?

**Comment by freyfogle** [comment]
never mind, I am able to recreate the bug, now working on a fix

**Comment by freyfogle** [comment]
ok I believe this is fixed in https://github.com/OpenCageData/address-formatting/commit/06317188b652fa22a9ac0dbd32b72c2f09bc4224

please can you test and if not submit a specific test case.
Gracias (as they say in Panama City City)

**Comment by brentodd** [comment]
Whoa - thanks for the fast fix!
