### ISSUE TITLE
possible issue with Italian address format as locally expected

### ISSUE THREAD

**Issue by sverx** [OpenCageData/address-formatting#98]
As you can see from [this example search](https://www.paginebianche.it/persone?qs=bono&dv=Roma%20(RM)) on the Italian white pages (phone book) website, there's _usually_ no comma between the street name and the house number, and the province code is _usually_ written between (round) brackets.

So for ex: **Via Garibaldi 123, 10123 Torino (TO)**
(I totally made up the address and the zip code, that's just to show the format)

in some cases there's even no house number so it's 's/n' or 's.n.c.'  => "senza numero civico" (means 'no house number')
For ex: **Strada Cantonale s/n, 20222 Rozzano (MI)**
(again, I totally made up the address and the zip code just to show the format)

**Comment by freyfogle** [comment]
Having looked at several websites, I definitely see some with the old format (street, house_number) but you are right that most do not have the comma. Thanks for making us aware.

This fix was merged and is now live for the OpenCage geocoding API, so closing this issue

**Comment by StephanGeorg** [comment]
I came across this issue because all our tests failed after updating a dependency. 

I have checked 1 million Italian postal addresses and their use in parcel delivery. Here is the outcome:

- **62.8%** : `street name, house number`
- **37.2%** : `street name house number`

I also checked whether this is a regional behavior, but couldn't see any pattern.

fyi @freyfogle @mtmail

**Comment by freyfogle** [comment]
@StephanGeorg what are you doing bringing data to a forum where decisions are traditionally based on anecdote?

On the other hand though, the Italian postal system seems to advise

```
Avoid using punctuation marks, underlining and special characters especially in lines 4, 5 and 6.
```

See https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/itaEn.pdf

Given that and the almost 40% split to not using comma, I am inclined to keep it as is (without comma).

Anyone have strong arguments the other way?

**Comment by StephanGeorg** [comment]
> On the other hand though, the Italian postal system seems to advise
> Avoid using punctuation marks, underlining and special characters especially in lines 4, 5 and 6.
> See https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/itaEn.pdf

Good point. Let's keep it as is.

> @StephanGeorg what are you doing bringing data to a forum where decisions are traditionally based on anecdote?

🤣 Don't look up! 😆

**Comment by sverx** [comment]
Also, all the examples from that PDF document doesn't have any comma between street name and number.

**Comment by freyfogle** [comment]
yes, agree, that said it also advises all addresses should be in ALL CAPS which doesn't seem realistic.

will close this issue again

**Comment by sverx** [comment]
Indeed ALL CAPS would be better.

Also, I just noticed that the Poste.it document contains a note and a following example that further confirm that the comma should **not** be used:
![image](https://github.com/OpenCageData/address-formatting/assets/6738932/5e87863a-07f4-4a3a-839d-44bc080263cc)
